version: 2.1
jobs:
  build:
    docker:
      - image: 'cimg/node:14.14.0'
        auth:
          username: endmaster0809
          password: $DOCKERHUB_PASSWORD
    steps:
      - run: node --version
