version: 2.1
orbs:
  node: circleci/node@4.0.0
jobs:
  build:
    docker:
      - image: 'cimg/node:14.14.0'
        auth:
          username: endmaster0809
          password: $DOCKERHUB_PASSWORD
    steps:
      - run: node --version
workflows:
  app-tests:
    jobs:
      - node/test